<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Produits extends \App\Entity\Produits implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'commandeProduits' => [parent::class, 'commandeProduits', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'id_categorie' => [parent::class, 'id_categorie', null],
        "\0".parent::class."\0".'image' => [parent::class, 'image', null],
        "\0".parent::class."\0".'nom' => [parent::class, 'nom', null],
        "\0".parent::class."\0".'prix' => [parent::class, 'prix', null],
        "\0".parent::class."\0".'quantite' => [parent::class, 'quantite', null],
        "\0".parent::class."\0".'seuil' => [parent::class, 'seuil', null],
        "\0".parent::class."\0".'unite_vente' => [parent::class, 'unite_vente', null],
        'commandeProduits' => [parent::class, 'commandeProduits', null],
        'id' => [parent::class, 'id', null],
        'id_categorie' => [parent::class, 'id_categorie', null],
        'image' => [parent::class, 'image', null],
        'nom' => [parent::class, 'nom', null],
        'prix' => [parent::class, 'prix', null],
        'quantite' => [parent::class, 'quantite', null],
        'seuil' => [parent::class, 'seuil', null],
        'unite_vente' => [parent::class, 'unite_vente', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
