<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Commandes extends \App\Entity\Commandes implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'commandeCGV' => [parent::class, 'commandeCGV', null],
        "\0".parent::class."\0".'commandePolitiqueConfidentialite' => [parent::class, 'commandePolitiqueConfidentialite', null],
        "\0".parent::class."\0".'commandeProduits' => [parent::class, 'commandeProduits', null],
        "\0".parent::class."\0".'commentaires' => [parent::class, 'commentaires', null],
        "\0".parent::class."\0".'date_commande' => [parent::class, 'date_commande', null],
        "\0".parent::class."\0".'date_recuperation' => [parent::class, 'date_recuperation', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'mail_client' => [parent::class, 'mail_client', null],
        "\0".parent::class."\0".'montant_total' => [parent::class, 'montant_total', null],
        "\0".parent::class."\0".'nom_client' => [parent::class, 'nom_client', null],
        "\0".parent::class."\0".'prenom_client' => [parent::class, 'prenom_client', null],
        "\0".parent::class."\0".'statut' => [parent::class, 'statut', null],
        "\0".parent::class."\0".'telephone_client' => [parent::class, 'telephone_client', null],
        'commandeCGV' => [parent::class, 'commandeCGV', null],
        'commandePolitiqueConfidentialite' => [parent::class, 'commandePolitiqueConfidentialite', null],
        'commandeProduits' => [parent::class, 'commandeProduits', null],
        'commentaires' => [parent::class, 'commentaires', null],
        'date_commande' => [parent::class, 'date_commande', null],
        'date_recuperation' => [parent::class, 'date_recuperation', null],
        'id' => [parent::class, 'id', null],
        'mail_client' => [parent::class, 'mail_client', null],
        'montant_total' => [parent::class, 'montant_total', null],
        'nom_client' => [parent::class, 'nom_client', null],
        'prenom_client' => [parent::class, 'prenom_client', null],
        'statut' => [parent::class, 'statut', null],
        'telephone_client' => [parent::class, 'telephone_client', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
