<?php

namespace Container9hQB2OB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_JFvOrQMService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.jFvOrQM' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.jFvOrQM'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'categorie' => ['privates', '.errored..service_locator.jFvOrQM.App\\Entity\\Categories', NULL, 'Cannot autowire service ".service_locator.jFvOrQM": it needs an instance of "App\\Entity\\Categories" but this type has been excluded in "config/services.yaml".'],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'categorie' => 'App\\Entity\\Categories',
            'em' => '?',
        ]);
    }
}
