<?php

namespace Container9hQB2OB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_ZKjv2D6Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.zKjv2D6' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.zKjv2D6'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'commande' => ['privates', '.errored..service_locator.zKjv2D6.App\\Entity\\Commandes', NULL, 'Cannot autowire service ".service_locator.zKjv2D6": it needs an instance of "App\\Entity\\Commandes" but this type has been excluded in "config/services.yaml".'],
        ], [
            'commande' => 'App\\Entity\\Commandes',
        ]);
    }
}
