<?php

namespace Container9hQB2OB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCommandesControllershowService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.zKjv2D6.App\Controller\CommandesController::show()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.zKjv2D6.App\\Controller\\CommandesController::show()'] = ($container->privates['.service_locator.zKjv2D6'] ?? $container->load('get_ServiceLocator_ZKjv2D6Service'))->withContext('App\\Controller\\CommandesController::show()', $container);
    }
}
