<?php

namespace Container9hQB2OB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCategoriesControllereditService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.jFvOrQM.App\Controller\CategoriesController::edit()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.jFvOrQM'] ?? $container->load('get_ServiceLocator_JFvOrQMService'));

        if (isset($container->privates['.service_locator.jFvOrQM.App\\Controller\\CategoriesController::edit()'])) {
            return $container->privates['.service_locator.jFvOrQM.App\\Controller\\CategoriesController::edit()'];
        }

        return $container->privates['.service_locator.jFvOrQM.App\\Controller\\CategoriesController::edit()'] = $a->withContext('App\\Controller\\CategoriesController::edit()', $container);
    }
}
