<?php

namespace Container9hQB2OB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCommandesControllerdeleteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.h_yWOzP.App\Controller\CommandesController::delete()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.h_yWOzP.App\\Controller\\CommandesController::delete()'] = ($container->privates['.service_locator.h_yWOzP'] ?? $container->load('get_ServiceLocator_HYWOzPService'))->withContext('App\\Controller\\CommandesController::delete()', $container);
    }
}
