<?php

namespace Container9hQB2OB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCommandesControllernewService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.j_M.nso.App\Controller\CommandesController::new()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.j_M.nso'] ?? $container->load('get_ServiceLocator_JM_NsoService'));

        if (isset($container->privates['.service_locator.j_M.nso.App\\Controller\\CommandesController::new()'])) {
            return $container->privates['.service_locator.j_M.nso.App\\Controller\\CommandesController::new()'];
        }

        return $container->privates['.service_locator.j_M.nso.App\\Controller\\CommandesController::new()'] = $a->withContext('App\\Controller\\CommandesController::new()', $container);
    }
}
