<?php

namespace Container9hQB2OB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCommandesControllerupdateQuantiteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Mj3oUpQ.App\Controller\CommandesController::updateQuantite()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.Mj3oUpQ'] ?? $container->load('get_ServiceLocator_Mj3oUpQService'));

        if (isset($container->privates['.service_locator.Mj3oUpQ.App\\Controller\\CommandesController::updateQuantite()'])) {
            return $container->privates['.service_locator.Mj3oUpQ.App\\Controller\\CommandesController::updateQuantite()'];
        }

        return $container->privates['.service_locator.Mj3oUpQ.App\\Controller\\CommandesController::updateQuantite()'] = $a->withContext('App\\Controller\\CommandesController::updateQuantite()', $container);
    }
}
