<?php

namespace Container9hQB2OB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getIndexControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.pj4fATd.App\Controller\IndexController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.pj4fATd.App\\Controller\\IndexController::index()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'categorieRepository' => ['privates', 'App\\Repository\\CategoriesRepository', 'getCategoriesRepositoryService', true],
            'produitRepository' => ['privates', 'App\\Repository\\ProduitsRepository', 'getProduitsRepositoryService', true],
            'tokenStorage' => ['privates', 'security.token_storage', 'getSecurity_TokenStorageService', false],
            'authChecker' => ['privates', 'security.authorization_checker', 'getSecurity_AuthorizationCheckerService', false],
            'paginator' => ['services', 'knp_paginator', 'getKnpPaginatorService', true],
            'reviewService' => ['privates', 'App\\Service\\ReviewService', 'getReviewServiceService', true],
        ], [
            'categorieRepository' => 'App\\Repository\\CategoriesRepository',
            'produitRepository' => 'App\\Repository\\ProduitsRepository',
            'tokenStorage' => '?',
            'authChecker' => '?',
            'paginator' => '?',
            'reviewService' => 'App\\Service\\ReviewService',
        ]))->withContext('App\\Controller\\IndexController::index()', $container);
    }
}
