<?php

namespace Container9hQB2OB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProduits2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.BhgNAKm.App\Entity\Produits' shared service.
     *
     * @return \App\Entity\Produits
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.BhgNAKm": it needs an instance of "App\\Entity\\Produits" but this type has been excluded in "config/services.yaml".');
    }
}
