<?php

namespace Container9hQB2OB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProduitControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.jY7WeMl.App\Controller\ProduitController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.jY7WeMl.App\\Controller\\ProduitController::index()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'produitRepo' => ['privates', 'App\\Repository\\ProduitsRepository', 'getProduitsRepositoryService', true],
            'categorieRepo' => ['privates', 'App\\Repository\\CategoriesRepository', 'getCategoriesRepositoryService', true],
            'paginator' => ['services', 'knp_paginator', 'getKnpPaginatorService', true],
        ], [
            'produitRepo' => 'App\\Repository\\ProduitsRepository',
            'categorieRepo' => 'App\\Repository\\CategoriesRepository',
            'paginator' => '?',
        ]))->withContext('App\\Controller\\ProduitController::index()', $container);
    }
}
