<?php

namespace Container9hQB2OB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProduitControllereditService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.BhgNAKm.App\Controller\ProduitController::edit()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.BhgNAKm.App\\Controller\\ProduitController::edit()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'produit' => ['privates', '.errored..service_locator.BhgNAKm.App\\Entity\\Produits', NULL, 'Cannot autowire service ".service_locator.BhgNAKm": it needs an instance of "App\\Entity\\Produits" but this type has been excluded in "config/services.yaml".'],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'produit' => 'App\\Entity\\Produits',
            'em' => '?',
        ]))->withContext('App\\Controller\\ProduitController::edit()', $container);
    }
}
