<?php

namespace Container9hQB2OB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRechercheControllersearchFormControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.15ElByP.App\Controller\RechercheController::searchFormController()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.15ElByP.App\\Controller\\RechercheController::searchFormController()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'categoriesRepository' => ['privates', 'App\\Repository\\CategoriesRepository', 'getCategoriesRepositoryService', true],
            'produitsRepository' => ['privates', 'App\\Repository\\ProduitsRepository', 'getProduitsRepositoryService', true],
        ], [
            'categoriesRepository' => 'App\\Repository\\CategoriesRepository',
            'produitsRepository' => 'App\\Repository\\ProduitsRepository',
        ]))->withContext('App\\Controller\\RechercheController::searchFormController()', $container);
    }
}
