<?php

namespace ContainerVDNLmgs;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Mj3oUpQService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Mj3oUpQ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Mj3oUpQ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'commande' => ['privates', '.errored..service_locator.Mj3oUpQ.App\\Entity\\Commandes', NULL, 'Cannot autowire service ".service_locator.Mj3oUpQ": it needs an instance of "App\\Entity\\Commandes" but this type has been excluded in "config/services.yaml".'],
            'mailer' => ['privates', 'mailer.mailer', 'getMailer_MailerService', true],
        ], [
            'entityManager' => '?',
            'commande' => 'App\\Entity\\Commandes',
            'mailer' => '?',
        ]);
    }
}
