<?php

namespace ContainerVDNLmgs;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAvisControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.FixhSYx.App\Controller\AvisController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.FixhSYx.App\\Controller\\AvisController::index()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'reviewService' => ['privates', 'App\\Service\\ReviewService', 'getReviewServiceService', true],
        ], [
            'reviewService' => 'App\\Service\\ReviewService',
        ]))->withContext('App\\Controller\\AvisController::index()', $container);
    }
}
