<?php

namespace ContainerVDNLmgs;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCommandesControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.INnH.PL.App\Controller\CommandesController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.INnH.PL.App\\Controller\\CommandesController::index()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'commandesRepository' => ['privates', 'App\\Repository\\CommandesRepository', 'getCommandesRepositoryService', true],
        ], [
            'commandesRepository' => 'App\\Repository\\CommandesRepository',
        ]))->withContext('App\\Controller\\CommandesController::index()', $container);
    }
}
