<?php

namespace ContainerVDNLmgs;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCommandes2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.h_yWOzP.App\Entity\Commandes' shared service.
     *
     * @return \App\Entity\Commandes
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.h_yWOzP": it needs an instance of "App\\Entity\\Commandes" but this type has been excluded in "config/services.yaml".');
    }
}
