<?php

namespace ContainerVDNLmgs;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCommandesControllereditService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.h_yWOzP.App\Controller\CommandesController::edit()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.h_yWOzP'] ?? $container->load('get_ServiceLocator_HYWOzPService'));

        if (isset($container->privates['.service_locator.h_yWOzP.App\\Controller\\CommandesController::edit()'])) {
            return $container->privates['.service_locator.h_yWOzP.App\\Controller\\CommandesController::edit()'];
        }

        return $container->privates['.service_locator.h_yWOzP.App\\Controller\\CommandesController::edit()'] = $a->withContext('App\\Controller\\CommandesController::edit()', $container);
    }
}
