<?php

namespace ContainerVDNLmgs;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCommandesControllerrecupereCommandeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Mj3oUpQ.App\Controller\CommandesController::recupereCommande()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Mj3oUpQ.App\\Controller\\CommandesController::recupereCommande()'] = ($container->privates['.service_locator.Mj3oUpQ'] ?? $container->load('get_ServiceLocator_Mj3oUpQService'))->withContext('App\\Controller\\CommandesController::recupereCommande()', $container);
    }
}
