<?php

namespace ContainerVDNLmgs;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPanierControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.jxYEFpF.App\Controller\PanierController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.jxYEFpF.App\\Controller\\PanierController::index()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'produitsRepository' => ['privates', 'App\\Repository\\ProduitsRepository', 'getProduitsRepositoryService', true],
        ], [
            'produitsRepository' => 'App\\Repository\\ProduitsRepository',
        ]))->withContext('App\\Controller\\PanierController::index()', $container);
    }
}
