<?php

namespace ContainerVDNLmgs;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPaiementControllersuccessService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.j_M.nso.App\Controller\PaiementController::success()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.j_M.nso'] ?? $container->load('get_ServiceLocator_JM_NsoService'));

        if (isset($container->privates['.service_locator.j_M.nso.App\\Controller\\PaiementController::success()'])) {
            return $container->privates['.service_locator.j_M.nso.App\\Controller\\PaiementController::success()'];
        }

        return $container->privates['.service_locator.j_M.nso.App\\Controller\\PaiementController::success()'] = $a->withContext('App\\Controller\\PaiementController::success()', $container);
    }
}
