<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container9hQB2OB\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container9hQB2OB/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container9hQB2OB.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container9hQB2OB\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container9hQB2OB\App_KernelDevDebugContainer([
    'container.build_hash' => '9hQB2OB',
    'container.build_id' => '8ff1fa63',
    'container.build_time' => 1748267092,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'Container9hQB2OB');
